name: duck-tools rust tests

on:
  push:
    paths:
      - "projects/duck-tools/**"
      - "projects/rpassword/**"
      - "projects/rprompt/**"

jobs:
  rust-linux-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install rust
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Run cargo test
        with:
          command: test
          args: --all-targets --all-features --manifest-path projects/duck-tools/Cargo.toml
