name: rpassword rust tests

on:
  push:
    paths:
      - "projects/rpassword/**"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install rust
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Run cargo test
        with:
          command: test
          args: --all-targets --all-features --manifest-path projects/rpassword/Cargo.toml
      - name: Run terminal tests
        run: ./tests/tests-unix.sh
        working-directory: projects/rpassword

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install rust
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Run cargo test
        with:
          command: test
          args: --all-targets --all-features --manifest-path projects/rpassword/Cargo.toml
